# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tsnotes',
                'doc_host': 'https://thigm85.github.io',
                'git_url': 'https://github.com/thigm85/tsnotes',
                'lib_path': 'tsnotes'},
  'syms': { 'tsnotes.core': { 'tsnotes.core.foo': ( 'https://thigm85.github.io/core.html#foo',
                                                    'https://github.com/thigm85/tsnotes/blob/master/tsnotes/core.py#L7')}}}